"""
Dataset Compiler for German Noun CEFR Levels (A1 to C1).
Compiles verified, high-frequency German nouns per CEFR level.
"""

import json
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

# ----------------------------------------------------------------------
# A1 NOUNS: Core Everyday Vocabulary (Family, Food, Home, Body, Time, Animals, City)
# ----------------------------------------------------------------------
A1_NOUNS = [
    # Family & People
    {"noun": "Mann", "article": "der", "plural": "Männer", "meaning": "man, husband", "level": "A1"},
    {"noun": "Frau", "article": "die", "plural": "Frauen", "meaning": "woman, wife", "level": "A1"},
    {"noun": "Kind", "article": "das", "plural": "Kinder", "meaning": "child", "level": "A1"},
    {"noun": "Baby", "article": "das", "plural": "Babys", "meaning": "baby", "level": "A1"},
    {"noun": "Junge", "article": "der", "plural": "Jungen", "meaning": "boy", "level": "A1"},
    {"noun": "Mädchen", "article": "das", "plural": "Mädchen", "meaning": "girl", "level": "A1"},
    {"noun": "Vater", "article": "der", "plural": "Väter", "meaning": "father", "level": "A1"},
    {"noun": "Mutter", "article": "die", "plural": "Mütter", "meaning": "mother", "level": "A1"},
    {"noun": "Eltern", "article": "die", "plural": "Eltern", "meaning": "parents", "level": "A1"},
    {"noun": "Sohn", "article": "der", "plural": "Söhne", "meaning": "son", "level": "A1"},
    {"noun": "Tochter", "article": "die", "plural": "Töchter", "meaning": "daughter", "level": "A1"},
    {"noun": "Bruder", "article": "der", "plural": "Brüder", "meaning": "brother", "level": "A1"},
    {"noun": "Schwester", "article": "die", "plural": "Schwestern", "meaning": "sister", "level": "A1"},
    {"noun": "Freund", "article": "der", "plural": "Freunde", "meaning": "friend (male)", "level": "A1"},
    {"noun": "Freundin", "article": "die", "plural": "Freundinnen", "meaning": "friend (female)", "level": "A1"},
    {"noun": "Familie", "article": "die", "plural": "Familien", "meaning": "family", "level": "A1"},
    {"noun": "Mensch", "article": "der", "plural": "Menschen", "meaning": "human, person", "level": "A1"},
    {"noun": "Leute", "article": "die", "plural": "Leute", "meaning": "people", "level": "A1"},
    {"noun": "Name", "article": "der", "plural": "Namen", "meaning": "name", "level": "A1"},

    # Animals
    {"noun": "Hund", "article": "der", "plural": "Hunde", "meaning": "dog", "level": "A1"},
    {"noun": "Katze", "article": "die", "plural": "Katzen", "meaning": "cat", "level": "A1"},
    {"noun": "Vogel", "article": "der", "plural": "Vögel", "meaning": "bird", "level": "A1"},
    {"noun": "Pferd", "article": "das", "plural": "Pferde", "meaning": "horse", "level": "A1"},
    {"noun": "Kuh", "article": "die", "plural": "Kühe", "meaning": "cow", "level": "A1"},
    {"noun": "Schwein", "article": "das", "plural": "Schweine", "meaning": "pig", "level": "A1"},
    {"noun": "Fisch", "article": "der", "plural": "Fische", "meaning": "fish", "level": "A1"},
    {"noun": "Tier", "article": "das", "plural": "Tiere", "meaning": "animal", "level": "A1"},

    # Food & Drinks
    {"noun": "Apfel", "article": "der", "plural": "Äpfel", "meaning": "apple", "level": "A1"},
    {"noun": "Banane", "article": "die", "plural": "Bananen", "meaning": "banana", "level": "A1"},
    {"noun": "Orange", "article": "die", "plural": "Orangen", "meaning": "orange", "level": "A1"},
    {"noun": "Brot", "article": "das", "plural": "Brote", "meaning": "bread", "level": "A1"},
    {"noun": "Brötchen", "article": "das", "plural": "Brötchen", "meaning": "bread roll", "level": "A1"},
    {"noun": "Butter", "article": "die", "plural": "Butter", "meaning": "butter", "level": "A1"},
    {"noun": "Käse", "article": "der", "plural": "Käse", "meaning": "cheese", "level": "A1"},
    {"noun": "Ei", "article": "das", "plural": "Eier", "meaning": "egg", "level": "A1"},
    {"noun": "Fleisch", "article": "das", "plural": "Fleisch", "meaning": "meat", "level": "A1"},
    {"noun": "Wurst", "article": "die", "plural": "Würste", "meaning": "sausage", "level": "A1"},
    {"noun": "Milch", "article": "die", "plural": "Milch", "meaning": "milk", "level": "A1"},
    {"noun": "Wasser", "article": "das", "plural": "Wässer", "meaning": "water", "level": "A1"},
    {"noun": "Kaffee", "article": "der", "plural": "Kaffees", "meaning": "coffee", "level": "A1"},
    {"noun": "Tee", "article": "der", "plural": "Tees", "meaning": "tea", "level": "A1"},
    {"noun": "Bier", "article": "das", "plural": "Biere", "meaning": "beer", "level": "A1"},
    {"noun": "Wein", "article": "der", "plural": "Weine", "meaning": "wine", "level": "A1"},
    {"noun": "Zucker", "article": "der", "plural": "Zucker", "meaning": "sugar", "level": "A1"},
    {"noun": "Salz", "article": "das", "plural": "Salze", "meaning": "salt", "level": "A1"},
    {"noun": "Pfeffer", "article": "der", "plural": "Pfeffer", "meaning": "pepper", "level": "A1"},
    {"noun": "Suppe", "article": "die", "plural": "Suppen", "meaning": "soup", "level": "A1"},
    {"noun": "Salat", "article": "der", "plural": "Salate", "meaning": "salad", "level": "A1"},
    {"noun": "Gemüse", "article": "das", "plural": "Gemüse", "meaning": "vegetables", "level": "A1"},
    {"noun": "Obst", "article": "das", "plural": "Obst", "meaning": "fruit", "level": "A1"},
    {"noun": "Kartoffel", "article": "die", "plural": "Kartoffeln", "meaning": "potato", "level": "A1"},
    {"noun": "Tomate", "article": "die", "plural": "Tomaten", "meaning": "tomato", "level": "A1"},
    {"noun": "Kuchen", "article": "der", "plural": "Kuchen", "meaning": "cake", "level": "A1"},
    {"noun": "Schokolade", "article": "die", "plural": "Schokoladen", "meaning": "chocolate", "level": "A1"},
    {"noun": "Eis", "article": "das", "plural": "Eis", "meaning": "ice cream, ice", "level": "A1"},
    {"noun": "Frühstück", "article": "das", "plural": "Frühstücke", "meaning": "breakfast", "level": "A1"},
    {"noun": "Mittagessen", "article": "das", "plural": "Mittagessen", "meaning": "lunch", "level": "A1"},
    {"noun": "Abendessen", "article": "das", "plural": "Abendessen", "meaning": "dinner", "level": "A1"},
    {"noun": "Essen", "article": "das", "plural": "Essen", "meaning": "food, meal", "level": "A1"},
    {"noun": "Getränk", "article": "das", "plural": "Getränke", "meaning": "drink, beverage", "level": "A1"},

    # House & Everyday Objects
    {"noun": "Haus", "article": "das", "plural": "Häuser", "meaning": "house", "level": "A1"},
    {"noun": "Wohnung", "article": "die", "plural": "Wohnungen", "meaning": "apartment, flat", "level": "A1"},
    {"noun": "Zimmer", "article": "das", "plural": "Zimmer", "meaning": "room", "level": "A1"},
    {"noun": "Küche", "article": "die", "plural": "Küchen", "meaning": "kitchen", "level": "A1"},
    {"noun": "Bad", "article": "das", "plural": "Bäder", "meaning": "bathroom, bath", "level": "A1"},
    {"noun": "Schlafzimmer", "article": "das", "plural": "Schlafzimmer", "meaning": "bedroom", "level": "A1"},
    {"noun": "Wohnzimmer", "article": "das", "plural": "Wohnzimmer", "meaning": "living room", "level": "A1"},
    {"noun": "Balkon", "article": "der", "plural": "Balkone", "meaning": "balcony", "level": "A1"},
    {"noun": "Garten", "article": "der", "plural": "Gärten", "meaning": "garden", "level": "A1"},
    {"noun": "Tür", "article": "die", "plural": "Türen", "meaning": "door", "level": "A1"},
    {"noun": "Fenster", "article": "das", "plural": "Fenster", "meaning": "window", "level": "A1"},
    {"noun": "Wand", "article": "die", "plural": "Wände", "meaning": "wall", "level": "A1"},
    {"noun": "Bett", "article": "das", "plural": "Betten", "meaning": "bed", "level": "A1"},
    {"noun": "Tisch", "article": "der", "plural": "Tische", "meaning": "table", "level": "A1"},
    {"noun": "Stuhl", "article": "der", "plural": "Stühle", "meaning": "chair", "level": "A1"},
    {"noun": "Schrank", "article": "der", "plural": "Schränke", "meaning": "cupboard, wardrobe", "level": "A1"},
    {"noun": "Sofa", "article": "das", "plural": "Sofas", "meaning": "sofa, couch", "level": "A1"},
    {"noun": "Lampe", "article": "die", "plural": "Lampen", "meaning": "lamp", "level": "A1"},
    {"noun": "Bild", "article": "das", "plural": "Bilder", "meaning": "picture", "level": "A1"},
    {"noun": "Schlüssel", "article": "der", "plural": "Schlüssel", "meaning": "key", "level": "A1"},
    {"noun": "Buch", "article": "das", "plural": "Bücher", "meaning": "book", "level": "A1"},
    {"noun": "Zeitung", "article": "die", "plural": "Zeitungen", "meaning": "newspaper", "level": "A1"},
    {"noun": "Stift", "article": "der", "plural": "Stifte", "meaning": "pen, pencil", "level": "A1"},
    {"noun": "Papier", "article": "das", "plural": "Papiere", "meaning": "paper", "level": "A1"},
    {"noun": "Tasche", "article": "die", "plural": "Taschen", "meaning": "bag, pocket", "level": "A1"},
    {"noun": "Uhr", "article": "die", "plural": "Uhren", "meaning": "clock, watch", "level": "A1"},
    {"noun": "Handy", "article": "das", "plural": "Handys", "meaning": "mobile phone", "level": "A1"},
    {"noun": "Computer", "article": "der", "plural": "Computer", "meaning": "computer", "level": "A1"},
    {"noun": "Fernseher", "article": "der", "plural": "Fernseher", "meaning": "television set", "level": "A1"},
    {"noun": "Glas", "article": "das", "plural": "Gläser", "meaning": "glass", "level": "A1"},
    {"noun": "Tasse", "article": "die", "plural": "Tassen", "meaning": "cup, mug", "level": "A1"},
    {"noun": "Teller", "article": "der", "plural": "Teller", "meaning": "plate", "level": "A1"},
    {"noun": "Messer", "article": "das", "plural": "Messer", "meaning": "knife", "level": "A1"},
    {"noun": "Gabel", "article": "die", "plural": "Gabeln", "meaning": "fork", "level": "A1"},
    {"noun": "Löffel", "article": "der", "plural": "Löffel", "meaning": "spoon", "level": "A1"},
    {"noun": "Flasche", "article": "die", "plural": "Flaschen", "meaning": "bottle", "level": "A1"},

    # Clothing
    {"noun": "Kleid", "article": "das", "plural": "Kleider", "meaning": "dress, clothes", "level": "A1"},
    {"noun": "Hose", "article": "die", "plural": "Hosen", "meaning": "trousers, pants", "level": "A1"},
    {"noun": "Hemd", "article": "das", "plural": "Hemden", "meaning": "shirt", "level": "A1"},
    {"noun": "T-Shirt", "article": "das", "plural": "T-Shirts", "meaning": "T-shirt", "level": "A1"},
    {"noun": "Jacke", "article": "die", "plural": "Jacken", "meaning": "jacket", "level": "A1"},
    {"noun": "Mantel", "article": "der", "plural": "Mäntel", "meaning": "coat", "level": "A1"},
    {"noun": "Schuh", "article": "der", "plural": "Schuhe", "meaning": "shoe", "level": "A1"},
    {"noun": "Rock", "article": "der", "plural": "Röcke", "meaning": "skirt", "level": "A1"},
    {"noun": "Pullover", "article": "der", "plural": "Pullover", "meaning": "sweater, jumper", "level": "A1"},
    {"noun": "Mütze", "article": "die", "plural": "Mützen", "meaning": "beanie, cap", "level": "A1"},
    {"noun": "Hut", "article": "der", "plural": "Hüte", "meaning": "hat", "level": "A1"},
    {"noun": "Brille", "article": "die", "plural": "Brillen", "meaning": "glasses", "level": "A1"},

    # Body & Health
    {"noun": "Kopf", "article": "der", "plural": "Köpfe", "meaning": "head", "level": "A1"},
    {"noun": "Auge", "article": "das", "plural": "Augen", "meaning": "eye", "level": "A1"},
    {"noun": "Ohr", "article": "das", "plural": "Ohren", "meaning": "ear", "level": "A1"},
    {"noun": "Nase", "article": "die", "plural": "Nasen", "meaning": "nose", "level": "A1"},
    {"noun": "Mund", "article": "der", "plural": "Münder", "meaning": "mouth", "level": "A1"},
    {"noun": "Zahn", "article": "der", "plural": "Zähne", "meaning": "tooth", "level": "A1"},
    {"noun": "Haar", "article": "das", "plural": "Haare", "meaning": "hair", "level": "A1"},
    {"noun": "Hand", "article": "die", "plural": "Hände", "meaning": "hand", "level": "A1"},
    {"noun": "Arm", "article": "der", "plural": "Arme", "meaning": "arm", "level": "A1"},
    {"noun": "Bein", "article": "das", "plural": "Beine", "meaning": "leg", "level": "A1"},
    {"noun": "Fuß", "article": "der", "plural": "Füße", "meaning": "foot", "level": "A1"},
    {"noun": "Bauch", "article": "der", "plural": "Bäuche", "meaning": "belly, stomach", "level": "A1"},
    {"noun": "Rücken", "article": "der", "plural": "Rücken", "meaning": "back", "level": "A1"},
    {"noun": "Arzt", "article": "der", "plural": "Ärzte", "meaning": "doctor (male)", "level": "A1"},
    {"noun": "Ärztin", "article": "die", "plural": "Ärztinnen", "meaning": "doctor (female)", "level": "A1"},
    {"noun": "Krankenhaus", "article": "das", "plural": "Krankenhäuser", "meaning": "hospital", "level": "A1"},
    {"noun": "Medikament", "article": "das", "plural": "Medikamente", "meaning": "medication, medicine", "level": "A1"},
    {"noun": "Apotheke", "article": "die", "plural": "Apotheken", "meaning": "pharmacy", "level": "A1"},

    # City, Transport & Places
    {"noun": "Stadt", "article": "die", "plural": "Städte", "meaning": "city, town", "level": "A1"},
    {"noun": "Land", "article": "das", "plural": "Länder", "meaning": "country, countryside", "level": "A1"},
    {"noun": "Straße", "article": "die", "plural": "Straßen", "meaning": "street, road", "level": "A1"},
    {"noun": "Platz", "article": "der", "plural": "Plätze", "meaning": "square, place, seat", "level": "A1"},
    {"noun": "Weg", "article": "der", "plural": "Wege", "meaning": "way, path", "level": "A1"},
    {"noun": "Auto", "article": "das", "plural": "Autos", "meaning": "car", "level": "A1"},
    {"noun": "Bus", "article": "der", "plural": "Busse", "meaning": "bus", "level": "A1"},
    {"noun": "Zug", "article": "der", "plural": "Züge", "meaning": "train", "level": "A1"},
    {"noun": "Bahn", "article": "die", "plural": "Bahnen", "meaning": "railway, train", "level": "A1"},
    {"noun": "Bahnhof", "article": "der", "plural": "Bahnhöfe", "meaning": "train station", "level": "A1"},
    {"noun": "Flughafen", "article": "der", "plural": "Flughäfen", "meaning": "airport", "level": "A1"},
    {"noun": "Flugzeug", "article": "das", "plural": "Flugzeuge", "meaning": "airplane", "level": "A1"},
    {"noun": "Fahrrad", "article": "das", "plural": "Fahrräder", "meaning": "bicycle", "level": "A1"},
    {"noun": "Schiff", "article": "das", "plural": "Schiffe", "meaning": "ship, boat", "level": "A1"},
    {"noun": "Ticket", "article": "das", "plural": "Tickets", "meaning": "ticket", "level": "A1"},
    {"noun": "Fahrkarte", "article": "die", "plural": "Fahrkarten", "meaning": "travel ticket", "level": "A1"},
    {"noun": "Hotel", "article": "das", "plural": "Hotels", "meaning": "hotel", "level": "A1"},
    {"noun": "Restaurant", "article": "das", "plural": "Restaurants", "meaning": "restaurant", "level": "A1"},
    {"noun": "Café", "article": "das", "plural": "Cafés", "meaning": "café", "level": "A1"},
    {"noun": "Supermarkt", "article": "der", "plural": "Supermärkte", "meaning": "supermarket", "level": "A1"},
    {"noun": "Laden", "article": "der", "plural": "Läden", "meaning": "shop, store", "level": "A1"},
    {"noun": "Markt", "article": "der", "plural": "Märkte", "meaning": "market", "level": "A1"},
    {"noun": "Bank", "article": "die", "plural": "Banken", "meaning": "bank (financial)", "level": "A1"},
    {"noun": "Post", "article": "die", "plural": "Post", "meaning": "post office, mail", "level": "A1"},
    {"noun": "Schule", "article": "die", "plural": "Schulen", "meaning": "school", "level": "A1"},
    {"noun": "Universität", "article": "die", "plural": "Universitäten", "meaning": "university", "level": "A1"},
    {"noun": "Park", "article": "der", "plural": "Parks", "meaning": "park", "level": "A1"},
    {"noun": "Meer", "article": "das", "plural": "Meere", "meaning": "sea, ocean", "level": "A1"},
    {"noun": "See", "article": "der", "plural": "Seen", "meaning": "lake", "level": "A1"},
    {"noun": "Fluss", "article": "der", "plural": "Flüsse", "meaning": "river", "level": "A1"},
    {"noun": "Berg", "article": "der", "plural": "Berge", "meaning": "mountain", "level": "A1"},
    {"noun": "Wald", "article": "der", "plural": "Wälder", "meaning": "forest, woods", "level": "A1"},
    {"noun": "Baum", "article": "der", "plural": "Bäume", "meaning": "tree", "level": "A1"},
    {"noun": "Blume", "article": "die", "plural": "Blumen", "meaning": "flower", "level": "A1"},
    {"noun": "Sonne", "article": "die", "plural": "Sonnen", "meaning": "sun", "level": "A1"},
    {"noun": "Mond", "article": "der", "plural": "Monde", "meaning": "moon", "level": "A1"},
    {"noun": "Stern", "article": "der", "plural": "Sterne", "meaning": "star", "level": "A1"},
    {"noun": "Himmel", "article": "der", "plural": "Himmel", "meaning": "sky, heaven", "level": "A1"},
    {"noun": "Wetter", "article": "das", "plural": "Wetter", "meaning": "weather", "level": "A1"},
    {"noun": "Regen", "article": "der", "plural": "Regen", "meaning": "rain", "level": "A1"},
    {"noun": "Schnee", "article": "der", "plural": "Schnee", "meaning": "snow", "level": "A1"},
    {"noun": "Wind", "article": "der", "plural": "Winde", "meaning": "wind", "level": "A1"},

    # Time, Calendar & Work
    {"noun": "Tag", "article": "der", "plural": "Tage", "meaning": "day", "level": "A1"},
    {"noun": "Nacht", "article": "die", "plural": "Nächte", "meaning": "night", "level": "A1"},
    {"noun": "Morgen", "article": "der", "plural": "Morgen", "meaning": "morning", "level": "A1"},
    {"noun": "Abend", "article": "der", "plural": "Abende", "meaning": "evening", "level": "A1"},
    {"noun": "Woche", "article": "die", "plural": "Wochen", "meaning": "week", "level": "A1"},
    {"noun": "Monat", "article": "der", "plural": "Monate", "meaning": "month", "level": "A1"},
    {"noun": "Jahr", "article": "das", "plural": "Jahre", "meaning": "year", "level": "A1"},
    {"noun": "Stunde", "article": "die", "plural": "Stunden", "meaning": "hour", "level": "A1"},
    {"noun": "Minute", "article": "die", "plural": "Minuten", "meaning": "minute", "level": "A1"},
    {"noun": "Sekunde", "article": "die", "plural": "Sekunden", "meaning": "second", "level": "A1"},
    {"noun": "Zeit", "article": "die", "plural": "Zeiten", "meaning": "time", "level": "A1"},
    {"noun": "Wochenende", "article": "das", "plural": "Wochenenden", "meaning": "weekend", "level": "A1"},
    {"noun": "Urlaub", "article": "der", "plural": "Urlaube", "meaning": "vacation, holiday", "level": "A1"},
    {"noun": "Ferien", "article": "die", "plural": "Ferien", "meaning": "school holidays", "level": "A1"},
    {"noun": "Arbeit", "article": "die", "plural": "Arbeiten", "meaning": "work, job", "level": "A1"},
    {"noun": "Beruf", "article": "der", "plural": "Berufe", "meaning": "profession, job", "level": "A1"},
    {"noun": "Geld", "article": "das", "plural": "Gelder", "meaning": "money", "level": "A1"},
    {"noun": "Euro", "article": "der", "plural": "Euro", "meaning": "euro", "level": "A1"},
    {"noun": "Cent", "article": "der", "plural": "Cent", "meaning": "cent", "level": "A1"},
    {"noun": "Preis", "article": "der", "plural": "Preise", "meaning": "price, prize", "level": "A1"},
    {"noun": "Rechnung", "article": "die", "plural": "Rechnungen", "meaning": "bill, invoice", "level": "A1"},
    {"noun": "Frage", "article": "die", "plural": "Fragen", "meaning": "question", "level": "A1"},
    {"noun": "Antwort", "article": "die", "plural": "Antworten", "meaning": "answer", "level": "A1"},
    {"noun": "Problem", "article": "das", "plural": "Probleme", "meaning": "problem", "level": "A1"},
    {"noun": "Hilfe", "article": "die", "plural": "Hilfen", "meaning": "help, assistance", "level": "A1"},
    {"noun": "Nummer", "article": "die", "plural": "Nummern", "meaning": "number", "level": "A1"},
    {"noun": "Wort", "article": "das", "plural": "Wörter", "meaning": "word", "level": "A1"},
    {"noun": "Satz", "article": "der", "plural": "Sätze", "meaning": "sentence", "level": "A1"},
    {"noun": "Sprache", "article": "die", "plural": "Sprachen", "meaning": "language", "level": "A1"}
]

with open(DATA_DIR / "nouns_a1.json", "w", encoding="utf-8") as f:
    json.dump(A1_NOUNS, f, ensure_ascii=False, indent=2)

print(f"✅ Generated A1 nouns dataset: {len(A1_NOUNS)} nouns")
