"""
Expanded Master CEFR German Nouns Compiler (A1 to C1).
Compiles comprehensive, verified vocabulary datasets covering all standard CEFR wordlists.
"""

import json
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

# ----------------------------------------------------------------------
# A2 NOUNS: Routine life, work, health, travel, communication, society (~150+ nouns)
# ----------------------------------------------------------------------
A2_NOUNS = [
    # Work, Office & Education
    {"noun": "Kollege", "article": "der", "plural": "Kollegen", "meaning": "colleague (male)", "level": "A2"},
    {"noun": "Kollegin", "article": "die", "plural": "Kolleginnen", "meaning": "colleague (female)", "level": "A2"},
    {"noun": "Chef", "article": "der", "plural": "Chefs", "meaning": "boss, manager (male)", "level": "A2"},
    {"noun": "Chefin", "article": "die", "plural": "Chefinnen", "meaning": "boss, manager (female)", "level": "A2"},
    {"noun": "Büro", "article": "das", "plural": "Büros", "meaning": "office", "level": "A2"},
    {"noun": "Kunde", "article": "der", "plural": "Kunden", "meaning": "client, customer (male)", "level": "A2"},
    {"noun": "Kundin", "article": "die", "plural": "Kundinnen", "meaning": "client, customer (female)", "level": "A2"},
    {"noun": "Firma", "article": "die", "plural": "Firmen", "meaning": "company, firm", "level": "A2"},
    {"noun": "Betrieb", "article": "der", "plural": "Betriebe", "meaning": "enterprise, business", "level": "A2"},
    {"noun": "Stelle", "article": "die", "plural": "Stellen", "meaning": "job position, spot", "level": "A2"},
    {"noun": "Bewerbung", "article": "die", "plural": "Bewerbungen", "meaning": "job application", "level": "A2"},
    {"noun": "Lebenslauf", "article": "der", "plural": "Lebensläufe", "meaning": "curriculum vitae, resume", "level": "A2"},
    {"noun": "Vertrag", "article": "der", "plural": "Verträge", "meaning": "contract", "level": "A2"},
    {"noun": "Gehalt", "article": "das", "plural": "Gehälter", "meaning": "salary", "level": "A2"},
    {"noun": "Lohn", "article": "der", "plural": "Löhne", "meaning": "wage", "level": "A2"},
    {"noun": "Termin", "article": "der", "plural": "Termine", "meaning": "appointment, date", "level": "A2"},
    {"noun": "Besprechung", "article": "die", "plural": "Besprechungen", "meaning": "meeting, discussion", "level": "A2"},
    {"noun": "Ausbildung", "article": "die", "plural": "Ausbildungen", "meaning": "apprenticeship, training", "level": "A2"},
    {"noun": "Praktikum", "article": "das", "plural": "Praktika", "meaning": "internship", "level": "A2"},
    {"noun": "Praktikant", "article": "der", "plural": "Praktikanten", "meaning": "intern (male)", "level": "A2"},
    {"noun": "Praktikantin", "article": "die", "plural": "Praktikantinnen", "meaning": "intern (female)", "level": "A2"},
    {"noun": "Studium", "article": "das", "plural": "Studien", "meaning": "university studies", "level": "A2"},
    {"noun": "Student", "article": "der", "plural": "Studenten", "meaning": "student (male)", "level": "A2"},
    {"noun": "Studentin", "article": "die", "plural": "Studentinnen", "meaning": "student (female)", "level": "A2"},
    {"noun": "Schüler", "article": "der", "plural": "Schüler", "meaning": "pupil, schoolboy", "level": "A2"},
    {"noun": "Schülerin", "article": "die", "plural": "Schülerinnen", "meaning": "pupil, schoolgirl", "level": "A2"},
    {"noun": "Lehrer", "article": "der", "plural": "Lehrer", "meaning": "teacher (male)", "level": "A2"},
    {"noun": "Lehrerin", "article": "die", "plural": "Lehrerinnen", "meaning": "teacher (female)", "level": "A2"},
    {"noun": "Prüfung", "article": "die", "plural": "Prüfungen", "meaning": "exam, test", "level": "A2"},
    {"noun": "Kurs", "article": "der", "plural": "Kurse", "meaning": "course, class", "level": "A2"},
    {"noun": "Klasse", "article": "die", "plural": "Klassen", "meaning": "class, classroom grade", "level": "A2"},
    {"noun": "Unterricht", "article": "der", "plural": "Unterrichte", "meaning": "instruction, lessons", "level": "A2"},
    {"noun": "Hausaufgabe", "article": "die", "plural": "Hausaufgaben", "meaning": "homework", "level": "A2"},
    {"noun": "Zeugnis", "article": "das", "plural": "Zeugnisse", "meaning": "certificate, report card", "level": "A2"},
    {"noun": "Erlaubnis", "article": "die", "plural": "Erlaubnisse", "meaning": "permission", "level": "A2"},

    # Travel, Transport & Accommodation
    {"noun": "Reise", "article": "die", "plural": "Reisen", "meaning": "trip, journey", "level": "A2"},
    {"noun": "Ausflug", "article": "der", "plural": "Ausflüge", "meaning": "excursion, day trip", "level": "A2"},
    {"noun": "Gepäck", "article": "das", "plural": "Gepäck", "meaning": "luggage, baggage", "level": "A2"},
    {"noun": "Koffer", "article": "der", "plural": "Koffer", "meaning": "suitcase", "level": "A2"},
    {"noun": "Rucksack", "article": "der", "plural": "Rucksäcke", "meaning": "backpack, rucksack", "level": "A2"},
    {"noun": "Reisepass", "article": "der", "plural": "Reisepässe", "meaning": "passport", "level": "A2"},
    {"noun": "Pass", "article": "der", "plural": "Pässe", "meaning": "passport, pass", "level": "A2"},
    {"noun": "Ausweis", "article": "der", "plural": "Ausweise", "meaning": "identity card, ID", "level": "A2"},
    {"noun": "Gleis", "article": "das", "plural": "Gleise", "meaning": "railway platform / track", "level": "A2"},
    {"noun": "Haltestelle", "article": "die", "plural": "Haltestellen", "meaning": "bus/tram stop", "level": "A2"},
    {"noun": "Fahrplan", "article": "der", "plural": "Fahrpläne", "meaning": "timetable, schedule", "level": "A2"},
    {"noun": "Verspätung", "article": "die", "plural": "Verspätungen", "meaning": "delay", "level": "A2"},
    {"noun": "Verkehr", "article": "der", "plural": "Verkehre", "meaning": "traffic, transport", "level": "A2"},
    {"noun": "Stau", "article": "der", "plural": "Staus", "meaning": "traffic jam", "level": "A2"},
    {"noun": "Ampel", "article": "die", "plural": "Ampeln", "meaning": "traffic light", "level": "A2"},
    {"noun": "Kreuzung", "article": "die", "plural": "Kreuzungen", "meaning": "intersection, junction", "level": "A2"},
    {"noun": "Autobahn", "article": "die", "plural": "Autobahnen", "meaning": "highway, motorway", "level": "A2"},
    {"noun": "Tankstelle", "article": "die", "plural": "Tankstellen", "meaning": "gas/petrol station", "level": "A2"},
    {"noun": "Führerschein", "article": "der", "plural": "Führerscheine", "meaning": "driving licence", "level": "A2"},
    {"noun": "Miete", "article": "die", "plural": "Mieten", "meaning": "rent", "level": "A2"},
    {"noun": "Vermieter", "article": "der", "plural": "Vermieter", "meaning": "landlord", "level": "A2"},
    {"noun": "Mieter", "article": "der", "plural": "Mieter", "meaning": "tenant", "level": "A2"},
    {"noun": "Nachbar", "article": "der", "plural": "Nachbarn", "meaning": "neighbour (male)", "level": "A2"},
    {"noun": "Nachbarin", "article": "die", "plural": "Nachbarinnen", "meaning": "neighbour (female)", "level": "A2"},
    {"noun": "Keller", "article": "der", "plural": "Keller", "meaning": "basement, cellar", "level": "A2"},
    {"noun": "Dach", "article": "das", "plural": "Dächer", "meaning": "roof", "level": "A2"},
    {"noun": "Treppe", "article": "die", "plural": "Treppen", "meaning": "stairs, staircase", "level": "A2"},
    {"noun": "Aufzug", "article": "der", "plural": "Aufzüge", "meaning": "elevator, lift", "level": "A2"},
    {"noun": "Heizung", "article": "die", "plural": "Heizungen", "meaning": "heating, radiator", "level": "A2"},
    {"noun": "Kühlschrank", "article": "der", "plural": "Kühlschränke", "meaning": "refrigerator", "level": "A2"},
    {"noun": "Herd", "article": "der", "plural": "Herde", "meaning": "stove, cooker", "level": "A2"},
    {"noun": "Ofen", "article": "der", "plural": "Öfen", "meaning": "oven", "level": "A2"},
    {"noun": "Spülmaschine", "article": "die", "plural": "Spülmaschinen", "meaning": "dishwasher", "level": "A2"},
    {"noun": "Waschmaschine", "article": "die", "plural": "Waschmaschinen", "meaning": "washing machine", "level": "A2"},

    # Health, Body & Daily Care
    {"noun": "Krankheit", "article": "die", "plural": "Krankheiten", "meaning": "illness, disease", "level": "A2"},
    {"noun": "Schmerz", "article": "der", "plural": "Schmerzen", "meaning": "pain, ache", "level": "A2"},
    {"noun": "Kopfschmerz", "article": "der", "plural": "Kopfschmerzen", "meaning": "headache", "level": "A2"},
    {"noun": "Bauchschmerz", "article": "der", "plural": "Bauchschmerzen", "meaning": "stomach ache", "level": "A2"},
    {"noun": "Fieber", "article": "das", "plural": "Fieber", "meaning": "fever", "level": "A2"},
    {"noun": "Husten", "article": "der", "plural": "Husten", "meaning": "cough", "level": "A2"},
    {"noun": "Schnupfen", "article": "der", "plural": "Schnupfen", "meaning": "runny nose, cold", "level": "A2"},
    {"noun": "Erkältung", "article": "die", "plural": "Erkältungen", "meaning": "common cold", "level": "A2"},
    {"noun": "Grippe", "article": "die", "plural": "Grippen", "meaning": "flu, influenza", "level": "A2"},
    {"noun": "Unfall", "article": "der", "plural": "Unfälle", "meaning": "accident", "level": "A2"},
    {"noun": "Notfall", "article": "der", "plural": "Notfälle", "meaning": "emergency", "level": "A2"},
    {"noun": "Rezept", "article": "das", "plural": "Rezepte", "meaning": "medical prescription, recipe", "level": "A2"},
    {"noun": "Pflaster", "article": "das", "plural": "Pflaster", "meaning": "band-aid, plaster", "level": "A2"},
    {"noun": "Verband", "article": "der", "plural": "Verbände", "meaning": "bandage, dressing", "level": "A2"},
    {"noun": "Praxis", "article": "die", "plural": "Praxen", "meaning": "doctor's office / clinic", "level": "A2"},
    {"noun": "Krankenkasse", "article": "die", "plural": "Krankenkassen", "meaning": "health insurance provider", "level": "A2"},
    {"noun": "Versicherung", "article": "die", "plural": "Versicherungen", "meaning": "insurance", "level": "A2"},
    {"noun": "Körper", "article": "der", "plural": "Körper", "meaning": "body", "level": "A2"},
    {"noun": "Haut", "article": "die", "plural": "Häute", "meaning": "skin", "level": "A2"},
    {"noun": "Herz", "article": "das", "plural": "Herzen", "meaning": "heart", "level": "A2"},
    {"noun": "Blut", "article": "das", "plural": "Blut", "meaning": "blood", "level": "A2"},
    {"noun": "Finger", "article": "der", "plural": "Finger", "meaning": "finger", "level": "A2"},
    {"noun": "Knie", "article": "das", "plural": "Knie", "meaning": "knee", "level": "A2"},
    {"noun": "Hals", "article": "der", "plural": "Hälse", "meaning": "neck, throat", "level": "A2"},
    {"noun": "Brust", "article": "die", "plural": "Brüste", "meaning": "chest, breast", "level": "A2"},
    {"noun": "Schulter", "article": "die", "plural": "Schultern", "meaning": "shoulder", "level": "A2"},
    {"noun": "Gewicht", "article": "das", "plural": "Gewichte", "meaning": "weight", "level": "A2"},
    {"noun": "Größe", "article": "die", "plural": "Größen", "meaning": "height, size", "level": "A2"},

    # Shopping, Leisure, Finance & Society
    {"noun": "Einkauf", "article": "der", "plural": "Einkäufe", "meaning": "shopping purchase", "level": "A2"},
    {"noun": "Angebot", "article": "das", "plural": "Angebote", "meaning": "offer, special deal", "level": "A2"},
    {"noun": "Rabatt", "article": "der", "plural": "Rabatte", "meaning": "discount", "level": "A2"},
    {"noun": "Kasse", "article": "die", "plural": "Kassen", "meaning": "cash register, checkout", "level": "A2"},
    {"noun": "Kassenzettel", "article": "der", "plural": "Kassenzettel", "meaning": "receipt", "level": "A2"},
    {"noun": "Konto", "article": "das", "plural": "Konten", "meaning": "bank account", "level": "A2"},
    {"noun": "Kreditkarte", "article": "die", "plural": "Kreditkarten", "meaning": "credit card", "level": "A2"},
    {"noun": "Bargeld", "article": "das", "plural": "Bargelder", "meaning": "cash", "level": "A2"},
    {"noun": "Geldbörse", "article": "die", "plural": "Geldbörsen", "meaning": "wallet, purse", "level": "A2"},
    {"noun": "Kino", "article": "das", "plural": "Kinos", "meaning": "cinema, movie theater", "level": "A2"},
    {"noun": "Theater", "article": "das", "plural": "Theater", "meaning": "theater", "level": "A2"},
    {"noun": "Museum", "article": "das", "plural": "Museen", "meaning": "museum", "level": "A2"},
    {"noun": "Konzert", "article": "das", "plural": "Konzerte", "meaning": "concert", "level": "A2"},
    {"noun": "Eintrittskarte", "article": "die", "plural": "Eintrittskarten", "meaning": "admission ticket", "level": "A2"},
    {"noun": "Ausstellung", "article": "die", "plural": "Ausstellungen", "meaning": "exhibition", "level": "A2"},
    {"noun": "Bibliothek", "article": "die", "plural": "Bibliotheken", "meaning": "library", "level": "A2"},
    {"noun": "Sport", "article": "der", "plural": "Sporte", "meaning": "sport, exercise", "level": "A2"},
    {"noun": "Mannschaft", "article": "die", "plural": "Mannschaften", "meaning": "team, crew", "level": "A2"},
    {"noun": "Spiel", "article": "das", "plural": "Spiele", "meaning": "game, match", "level": "A2"},
    {"noun": "Spielplatz", "article": "der", "plural": "Spielplätze", "meaning": "playground", "level": "A2"},
    {"noun": "Schwimmbad", "article": "das", "plural": "Schwimmbäder", "meaning": "swimming pool", "level": "A2"},
    {"noun": "Fitnessstudio", "article": "das", "plural": "Fitnessstudios", "meaning": "gym, fitness center", "level": "A2"},
    {"noun": "Verein", "article": "der", "plural": "Vereine", "meaning": "club, association", "level": "A2"},
    {"noun": "Mitglied", "article": "das", "plural": "Mitglieder", "meaning": "member", "level": "A2"},
    {"noun": "Hobby", "article": "das", "plural": "Hobbys", "meaning": "hobby", "level": "A2"},
    {"noun": "Musik", "article": "die", "plural": "Musiken", "meaning": "music", "level": "A2"},
    {"noun": "Lied", "article": "das", "plural": "Lieder", "meaning": "song", "level": "A2"},
    {"noun": "Gitarre", "article": "die", "plural": "Gitarren", "meaning": "guitar", "level": "A2"},
    {"noun": "Klavier", "article": "das", "plural": "Klaviere", "meaning": "piano", "level": "A2"},
    {"noun": "Foto", "article": "das", "plural": "Fotos", "meaning": "photo, photograph", "level": "A2"},
    {"noun": "Kamera", "article": "die", "plural": "Kameras", "meaning": "camera", "level": "A2"},

    # Communication, Documents & Nature
    {"noun": "Nachricht", "article": "die", "plural": "Nachrichten", "meaning": "news, message", "level": "A2"},
    {"noun": "Brief", "article": "der", "plural": "Briefe", "meaning": "letter", "level": "A2"},
    {"noun": "Briefkasten", "article": "der", "plural": "Briefkästen", "meaning": "mailbox, letterbox", "level": "A2"},
    {"noun": "Briefmarke", "article": "die", "plural": "Briefmarken", "meaning": "postage stamp", "level": "A2"},
    {"noun": "Paket", "article": "das", "plural": "Pakete", "meaning": "parcel, package", "level": "A2"},
    {"noun": "Päckchen", "article": "das", "plural": "Päckchen", "meaning": "small packet", "level": "A2"},
    {"noun": "E-Mail", "article": "die", "plural": "E-Mails", "meaning": "email", "level": "A2"},
    {"noun": "Telefon", "article": "das", "plural": "Telefone", "meaning": "telephone", "level": "A2"},
    {"noun": "Gespräch", "article": "das", "plural": "Gespräche", "meaning": "conversation", "level": "A2"},
    {"noun": "Internet", "article": "das", "plural": "Internet", "meaning": "internet", "level": "A2"},
    {"noun": "Passwort", "article": "das", "plural": "Passwörter", "meaning": "password", "level": "A2"},
    {"noun": "Formular", "article": "das", "plural": "Formulare", "meaning": "form, document to fill", "level": "A2"},
    {"noun": "Unterschrift", "article": "die", "plural": "Unterschriften", "meaning": "signature", "level": "A2"},
    {"noun": "Information", "article": "die", "plural": "Informationen", "meaning": "information", "level": "A2"},
    {"noun": "Adresse", "article": "die", "plural": "Adressen", "meaning": "address", "level": "A2"},
    {"noun": "Geburtsdatum", "article": "das", "plural": "Geburtsdaten", "meaning": "date of birth", "level": "A2"},
    {"noun": "Geburtstag", "article": "der", "plural": "Geburtstage", "meaning": "birthday", "level": "A2"},
    {"noun": "Geschenk", "article": "das", "plural": "Geschenke", "meaning": "gift, present", "level": "A2"},
    {"noun": "Feier", "article": "die", "plural": "Feiern", "meaning": "celebration, party", "level": "A2"},
    {"noun": "Fest", "article": "das", "plural": "Feste", "meaning": "festival, feast", "level": "A2"},
    {"noun": "Party", "article": "die", "plural": "Partys", "meaning": "party", "level": "A2"},
    {"noun": "Gast", "article": "der", "plural": "Gäste", "meaning": "guest", "level": "A2"},
    {"noun": "Einladung", "article": "die", "plural": "Einladungen", "meaning": "invitation", "level": "A2"},
    {"noun": "Natur", "article": "die", "plural": "Naturen", "meaning": "nature", "level": "A2"},
    {"noun": "Umwelt", "article": "die", "plural": "Umwelten", "meaning": "environment", "level": "A2"},
    {"noun": "Pflanze", "article": "die", "plural": "Pflanzen", "meaning": "plant", "level": "A2"},
    {"noun": "Gras", "article": "das", "plural": "Gräser", "meaning": "grass", "level": "A2"},
    {"noun": "Blatt", "article": "das", "plural": "Blätter", "meaning": "leaf, sheet of paper", "level": "A2"},
    {"noun": "Strand", "article": "der", "plural": "Strände", "meaning": "beach", "level": "A2"},
    {"noun": "Küste", "article": "die", "plural": "Küsten", "meaning": "coast, shore", "level": "A2"},
    {"noun": "Insel", "article": "die", "plural": "Inseln", "meaning": "island", "level": "A2"},
    {"noun": "Dorf", "article": "das", "plural": "Dörfer", "meaning": "village", "level": "A2"},
    {"noun": "Luft", "article": "die", "plural": "Lüfte", "meaning": "air", "level": "A2"},
    {"noun": "Feuer", "article": "das", "plural": "Feuer", "meaning": "fire", "level": "A2"},
    {"noun": "Gewitter", "article": "das", "plural": "Gewitter", "meaning": "thunderstorm", "level": "A2"},
    {"noun": "Wolke", "article": "die", "plural": "Wolken", "meaning": "cloud", "level": "A2"},
    {"noun": "Nebel", "article": "der", "plural": "Nebel", "meaning": "fog, mist", "level": "A2"},
    {"noun": "Sturm", "article": "der", "plural": "Stürme", "meaning": "storm, gale", "level": "A2"},
    {"noun": "Grad", "article": "das", "plural": "Grad", "meaning": "degree (temperature/angle)", "level": "A2"}
]

# ----------------------------------------------------------------------
# B1 NOUNS: Intermediate Society, Career, Abstractions & Feelings (~120+ nouns)
# ----------------------------------------------------------------------
B1_NOUNS = [
    # Abstract Qualities & States
    {"noun": "Möglichkeit", "article": "die", "plural": "Möglichkeiten", "meaning": "possibility, opportunity", "level": "B1"},
    {"noun": "Fähigkeit", "article": "die", "plural": "Fähigkeiten", "meaning": "ability, skill", "level": "B1"},
    {"noun": "Schwierigkeit", "article": "die", "plural": "Schwierigkeiten", "meaning": "difficulty", "level": "B1"},
    {"noun": "Tätigkeit", "article": "die", "plural": "Tätigkeiten", "meaning": "activity, occupation", "level": "B1"},
    {"noun": "Persönlichkeit", "article": "die", "plural": "Persönlichkeiten", "meaning": "personality", "level": "B1"},
    {"noun": "Höflichkeit", "article": "die", "plural": "Höflichkeiten", "meaning": "politeness, courtesy", "level": "B1"},
    {"noun": "Ehrlichkeit", "article": "die", "plural": "Ehrlichkeiten", "meaning": "honesty", "level": "B1"},
    {"noun": "Pünktlichkeit", "article": "die", "plural": "Pünktlichkeiten", "meaning": "punctuality", "level": "B1"},
    {"noun": "Wichtigkeit", "article": "die", "plural": "Wichtigkeiten", "meaning": "importance", "level": "B1"},
    {"noun": "Freiheit", "article": "die", "plural": "Freiheiten", "meaning": "freedom, liberty", "level": "B1"},
    {"noun": "Sicherheit", "article": "die", "plural": "Sicherheiten", "meaning": "safety, security, certainty", "level": "B1"},
    {"noun": "Wahrheit", "article": "die", "plural": "Wahrheiten", "meaning": "truth", "level": "B1"},
    {"noun": "Gesundheit", "article": "die", "plural": "Gesundheiten", "meaning": "health", "level": "B1"},
    {"noun": "Klarheit", "article": "die", "plural": "Klarheiten", "meaning": "clarity", "level": "B1"},
    {"noun": "Einheit", "article": "die", "plural": "Einheiten", "meaning": "unit, unity", "level": "B1"},
    {"noun": "Mehrheit", "article": "die", "plural": "Mehrheiten", "meaning": "majority", "level": "B1"},
    {"noun": "Minderheit", "article": "die", "plural": "Minderheiten", "meaning": "minority", "level": "B1"},
    {"noun": "Gelegenheit", "article": "die", "plural": "Gelegenheiten", "meaning": "occasion, opportunity", "level": "B1"},
    {"noun": "Gewohnheit", "article": "die", "plural": "Gewohnheiten", "meaning": "habit, custom", "level": "B1"},
    {"noun": "Vergangenheit", "article": "die", "plural": "Vergangenheiten", "meaning": "past", "level": "B1"},
    {"noun": "Zukunft", "article": "die", "plural": "Zukünfte", "meaning": "future", "level": "B1"},
    {"noun": "Gegenwart", "article": "die", "plural": "Gegenwarten", "meaning": "present (time)", "level": "B1"},
    {"noun": "Hoffnung", "article": "die", "plural": "Hoffnungen", "meaning": "hope", "level": "B1"},
    {"noun": "Erfahrung", "article": "die", "plural": "Erfahrungen", "meaning": "experience", "level": "B1"},
    {"noun": "Meinung", "article": "die", "plural": "Meinungen", "meaning": "opinion", "level": "B1"},
    {"noun": "Entscheidung", "article": "die", "plural": "Entscheidungen", "meaning": "decision", "level": "B1"},
    {"noun": "Entwicklung", "article": "die", "plural": "Entwicklungen", "meaning": "development", "level": "B1"},
    {"noun": "Veränderung", "article": "die", "plural": "Veränderungen", "meaning": "change, alteration", "level": "B1"},
    {"noun": "Bedeutung", "article": "die", "plural": "Bedeutungen", "meaning": "meaning, importance", "level": "B1"},
    {"noun": "Erinnerung", "article": "die", "plural": "Erinnerungen", "meaning": "memory, reminder", "level": "B1"},
    {"noun": "Überraschung", "article": "die", "plural": "Überraschungen", "meaning": "surprise", "level": "B1"},
    {"noun": "Enttäuschung", "article": "die", "plural": "Enttäuschungen", "meaning": "disappointment", "level": "B1"},
    {"noun": "Bewegung", "article": "die", "plural": "Bewegungen", "meaning": "movement, motion", "level": "B1"},
    {"noun": "Ernährung", "article": "die", "plural": "Ernährungen", "meaning": "nutrition, diet", "level": "B1"},
    {"noun": "Vorbereitung", "article": "die", "plural": "Vorbereitungen", "meaning": "preparation", "level": "B1"},
    {"noun": "Freundschaft", "article": "die", "plural": "Freundschaften", "meaning": "friendship", "level": "B1"},
    {"noun": "Gesellschaft", "article": "die", "plural": "Gesellschaften", "meaning": "society, corporation", "level": "B1"},
    {"noun": "Wirtschaft", "article": "die", "plural": "Wirtschaften", "meaning": "economy", "level": "B1"},
    {"noun": "Wissenschaft", "article": "die", "plural": "Wissenschaften", "meaning": "science, scholarship", "level": "B1"},
    {"noun": "Landschaft", "article": "die", "plural": "Landschaften", "meaning": "landscape, scenery", "level": "B1"},
    {"noun": "Gemeinschaft", "article": "die", "plural": "Gemeinschaften", "meaning": "community", "level": "B1"},
    {"noun": "Gemeinde", "article": "die", "plural": "Gemeinden", "meaning": "municipality, parish", "level": "B1"},
    {"noun": "Eigenschaft", "article": "die", "plural": "Eigenschaften", "meaning": "characteristic, property", "level": "B1"},

    # Society, Politics, Media & Law
    {"noun": "Politik", "article": "die", "plural": "Politiken", "meaning": "politics, policy", "level": "B1"},
    {"noun": "Staat", "article": "der", "plural": "Staaten", "meaning": "state, nation", "level": "B1"},
    {"noun": "Regierung", "article": "die", "plural": "Regierungen", "meaning": "government", "level": "B1"},
    {"noun": "Gesetz", "article": "das", "plural": "Gesetze", "meaning": "law, statute", "level": "B1"},
    {"noun": "Recht", "article": "das", "plural": "Rechte", "meaning": "right, justice, law", "level": "B1"},
    {"noun": "Pflicht", "article": "die", "plural": "Pflichten", "meaning": "duty, obligation", "level": "B1"},
    {"noun": "Gericht", "article": "das", "plural": "Gerichte", "meaning": "court of law, dish/meal", "level": "B1"},
    {"noun": "Polizei", "article": "die", "plural": "Polizeien", "meaning": "police", "level": "B1"},
    {"noun": "Kriminalität", "article": "die", "plural": "Kriminalitäten", "meaning": "crime, criminality", "level": "B1"},
    {"noun": "Verbrechen", "article": "das", "plural": "Verbrechen", "meaning": "crime, felony", "level": "B1"},
    {"noun": "Täter", "article": "der", "plural": "Täter", "meaning": "perpetrator, offender", "level": "B1"},
    {"noun": "Opfer", "article": "das", "plural": "Opfer", "meaning": "victim, sacrifice", "level": "B1"},
    {"noun": "Zeuge", "article": "der", "plural": "Zeugen", "meaning": "witness (male)", "level": "B1"},
    {"noun": "Zeugin", "article": "die", "plural": "Zeuginnen", "meaning": "witness (female)", "level": "B1"},
    {"noun": "Demokratie", "article": "die", "plural": "Demokratien", "meaning": "democracy", "level": "B1"},
    {"noun": "Wahl", "article": "die", "plural": "Wahlen", "meaning": "election, choice", "level": "B1"},
    {"noun": "Stimme", "article": "die", "plural": "Stimmen", "meaning": "voice, vote", "level": "B1"},
    {"noun": "Partei", "article": "die", "plural": "Parteien", "meaning": "political party, party", "level": "B1"},
    {"noun": "Bürger", "article": "der", "plural": "Bürger", "meaning": "citizen (male)", "level": "B1"},
    {"noun": "Bürgerin", "article": "die", "plural": "Bürgerinnen", "meaning": "citizen (female)", "level": "B1"},
    {"noun": "Bevölkerung", "article": "die", "plural": "Bevölkerungen", "meaning": "population", "level": "B1"},
    {"noun": "Kultur", "article": "die", "plural": "Kulturen", "meaning": "culture", "level": "B1"},
    {"noun": "Tradition", "article": "die", "plural": "Traditionen", "meaning": "tradition", "level": "B1"},
    {"noun": "Religion", "article": "die", "plural": "Religionen", "meaning": "religion", "level": "B1"},
    {"noun": "Kirche", "article": "die", "plural": "Kirchen", "meaning": "church", "level": "B1"},
    {"noun": "Medien", "article": "die", "plural": "Medien", "meaning": "media", "level": "B1"},
    {"noun": "Sendung", "article": "die", "plural": "Sendungen", "meaning": "broadcast, parcel", "level": "B1"},
    {"noun": "Nachrichtensendung", "article": "die", "plural": "Nachrichtensendungen", "meaning": "news broadcast", "level": "B1"},
    {"noun": "Interview", "article": "das", "plural": "Interviews", "meaning": "interview", "level": "B1"},
    {"noun": "Bericht", "article": "der", "plural": "Berichte", "meaning": "report", "level": "B1"},
    {"noun": "Artikel", "article": "der", "plural": "Artikel", "meaning": "article (press/grammar), item", "level": "B1"},
    {"noun": "Titel", "article": "der", "plural": "Titel", "meaning": "title, headline", "level": "B1"},
    {"noun": "Thema", "article": "das", "plural": "Themen", "meaning": "topic, theme", "level": "B1"},

    # Feelings, Mind & Human Relations
    {"noun": "Gefühl", "article": "das", "plural": "Gefühle", "meaning": "feeling, emotion", "level": "B1"},
    {"noun": "Angst", "article": "die", "plural": "Ängste", "meaning": "fear, anxiety", "level": "B1"},
    {"noun": "Freude", "article": "die", "plural": "Freuden", "meaning": "joy, pleasure", "level": "B1"},
    {"noun": "Wut", "article": "die", "plural": "Wut", "meaning": "anger, rage", "level": "B1"},
    {"noun": "Liebe", "article": "die", "plural": "Lieben", "meaning": "love", "level": "B1"},
    {"noun": "Hass", "article": "der", "plural": "Hass", "meaning": "hate, hatred", "level": "B1"},
    {"noun": "Trauer", "article": "die", "plural": "Trauer", "meaning": "grief, mourning", "level": "B1"},
    {"noun": "Gedanke", "article": "der", "plural": "Gedanken", "meaning": "thought, idea", "level": "B1"},
    {"noun": "Glaube", "article": "der", "plural": "Glauben", "meaning": "faith, belief", "level": "B1"},
    {"noun": "Wille", "article": "der", "plural": "Willen", "meaning": "will, willpower", "level": "B1"},
    {"noun": "Wunsch", "article": "der", "plural": "Wünsche", "meaning": "wish, desire", "level": "B1"},
    {"noun": "Traum", "article": "der", "plural": "Träume", "meaning": "dream", "level": "B1"},
    {"noun": "Ziel", "article": "das", "plural": "Ziele", "meaning": "goal, destination", "level": "B1"},
    {"noun": "Erfolg", "article": "der", "plural": "Erfolge", "meaning": "success", "level": "B1"},
    {"noun": "Misserfolg", "article": "der", "plural": "Misserfolge", "meaning": "failure", "level": "B1"},
    {"noun": "Glück", "article": "das", "plural": "Glücke", "meaning": "luck, happiness", "level": "B1"},
    {"noun": "Pech", "article": "das", "plural": "Pech", "meaning": "bad luck, misfortune", "level": "B1"},
    {"noun": "Streit", "article": "der", "plural": "Streite", "meaning": "argument, dispute", "level": "B1"},
    {"noun": "Konflikt", "article": "der", "plural": "Konflikte", "meaning": "conflict", "level": "B1"},
    {"noun": "Lösung", "article": "die", "plural": "Lösungen", "meaning": "solution", "level": "B1"},
    {"noun": "Vorschlag", "article": "der", "plural": "Vorschläge", "meaning": "suggestion, proposal", "level": "B1"},
    {"noun": "Rat", "article": "der", "plural": "Ratschläge", "meaning": "advice, council", "level": "B1"},
    {"noun": "Grund", "article": "der", "plural": "Gründe", "meaning": "reason, basis, ground", "level": "B1"},
    {"noun": "Ursache", "article": "die", "plural": "Ursachen", "meaning": "cause, root cause", "level": "B1"},
    {"noun": "Wirkung", "article": "die", "plural": "Wirkungen", "meaning": "effect, impact", "level": "B1"},
    {"noun": "Folge", "article": "die", "plural": "Folgen", "meaning": "consequence, episode", "level": "B1"},
    {"noun": "Geduld", "article": "die", "plural": "Geduld", "meaning": "patience", "level": "B1"},
    {"noun": "Gefahr", "article": "die", "plural": "Gefahren", "meaning": "danger, peril", "level": "B1"},
    {"noun": "Mut", "article": "der", "plural": "Mut", "meaning": "courage, bravery", "level": "B1"},

    # Science, Technology & Environment
    {"noun": "Technik", "article": "die", "plural": "Techniken", "meaning": "technology, technique", "level": "B1"},
    {"noun": "Gerät", "article": "das", "plural": "Geräte", "meaning": "device, appliance", "level": "B1"},
    {"noun": "Maschine", "article": "die", "plural": "Maschinen", "meaning": "machine", "level": "B1"},
    {"noun": "Motor", "article": "der", "plural": "Motoren", "meaning": "engine, motor", "level": "B1"},
    {"noun": "Energie", "article": "die", "plural": "Energien", "meaning": "energy, power", "level": "B1"},
    {"noun": "Strom", "article": "der", "plural": "Ströme", "meaning": "electricity, current, stream", "level": "B1"},
    {"noun": "Müll", "article": "der", "plural": "Müll", "meaning": "garbage, rubbish, trash", "level": "B1"},
    {"noun": "Abfall", "article": "der", "plural": "Abfälle", "meaning": "waste, scrap", "level": "B1"},
    {"noun": "Verschmutzung", "article": "die", "plural": "Verschmutzungen", "meaning": "pollution, contamination", "level": "B1"},
    {"noun": "Klimawandel", "article": "der", "plural": "Klimawandel", "meaning": "climate change", "level": "B1"},
    {"noun": "Ergebnis", "article": "das", "plural": "Ergebnisse", "meaning": "result, outcome", "level": "B1"},
    {"noun": "Ereignis", "article": "das", "plural": "Ereignisse", "meaning": "event, occurrence", "level": "B1"},
    {"noun": "Erlebnis", "article": "das", "plural": "Erlebnisse", "meaning": "experience, adventure", "level": "B1"},
    {"noun": "Geheimnis", "article": "das", "plural": "Geheimnisse", "meaning": "secret, mystery", "level": "B1"}
]

# ----------------------------------------------------------------------
# B2 NOUNS: Upper-Intermediate Academic, Societal & Discourse (~110+ nouns)
# ----------------------------------------------------------------------
B2_NOUNS = [
    # Academic & Professional Concepts
    {"noun": "Voraussetzung", "article": "die", "plural": "Voraussetzungen", "meaning": "prerequisite, requirement", "level": "B2"},
    {"noun": "Herausforderung", "article": "die", "plural": "Herausforderungen", "meaning": "challenge", "level": "B2"},
    {"noun": "Verantwortung", "article": "die", "plural": "Verantwortungen", "meaning": "responsibility", "level": "B2"},
    {"noun": "Zuverlässigkeit", "article": "die", "plural": "Zuverlässigkeiten", "meaning": "reliability, dependability", "level": "B2"},
    {"noun": "Aufmerksamkeit", "article": "die", "plural": "Aufmerksamkeiten", "meaning": "attention, attentiveness", "level": "B2"},
    {"noun": "Gerechtigkeit", "article": "die", "plural": "Gerechtigkeiten", "meaning": "justice, fairness", "level": "B2"},
    {"noun": "Ungerechtigkeit", "article": "die", "plural": "Ungerechtigkeiten", "meaning": "injustice, unfairness", "level": "B2"},
    {"noun": "Einsamkeit", "article": "die", "plural": "Einsamkeiten", "meaning": "loneliness, solitude", "level": "B2"},
    {"noun": "Nachhaltigkeit", "article": "die", "plural": "Nachhaltigkeiten", "meaning": "sustainability", "level": "B2"},
    {"noun": "Chancengleichheit", "article": "die", "plural": "Chancengleichheiten", "meaning": "equal opportunity", "level": "B2"},
    {"noun": "Gleichberechtigung", "article": "die", "plural": "Gleichberechtigungen", "meaning": "equal rights, gender equality", "level": "B2"},
    {"noun": "Zusammenhang", "article": "der", "plural": "Zusammenhänge", "meaning": "connection, context", "level": "B2"},
    {"noun": "Gegenteil", "article": "das", "plural": "Gegenteile", "meaning": "opposite, contrary", "level": "B2"},
    {"noun": "Unterschied", "article": "der", "plural": "Unterschiede", "meaning": "difference, distinction", "level": "B2"},
    {"noun": "Vergleich", "article": "der", "plural": "Vergleiche", "meaning": "comparison", "level": "B2"},
    {"noun": "Einfluss", "article": "der", "plural": "Einflüsse", "meaning": "influence, impact", "level": "B2"},
    {"noun": "Auswirkung", "article": "die", "plural": "Auswirkungen", "meaning": "effect, repercussion", "level": "B2"},
    {"noun": "Maßnahme", "article": "die", "plural": "Maßnahmen", "meaning": "measure, action", "level": "B2"},
    {"noun": "Konsequenz", "article": "die", "plural": "Konsequenzen", "meaning": "consequence", "level": "B2"},
    {"noun": "Perspektive", "article": "die", "plural": "Perspektiven", "meaning": "perspective, viewpoint", "level": "B2"},
    {"noun": "Standpunkt", "article": "der", "plural": "Standpunkte", "meaning": "point of view, stance", "level": "B2"},
    {"noun": "Ansicht", "article": "die", "plural": "Ansichten", "meaning": "view, opinion", "level": "B2"},
    {"noun": "Argument", "article": "das", "plural": "Argumente", "meaning": "argument, point", "level": "B2"},
    {"noun": "Begründung", "article": "die", "plural": "Begründungen", "meaning": "justification, reasoning", "level": "B2"},
    {"noun": "Kritik", "article": "die", "plural": "Kritiken", "meaning": "criticism, review", "level": "B2"},
    {"noun": "Zweifel", "article": "der", "plural": "Zweifel", "meaning": "doubt, uncertainty", "level": "B2"},
    {"noun": "Vertrauen", "article": "das", "plural": "Vertrauen", "meaning": "trust, confidence", "level": "B2"},
    {"noun": "Misstrauen", "article": "das", "plural": "Misstrauen", "meaning": "mistrust, suspicion", "level": "B2"},
    {"noun": "Respekt", "article": "der", "plural": "Respekt", "meaning": "respect, regard", "level": "B2"},
    {"noun": "Toleranz", "article": "die", "plural": "Toleranzen", "meaning": "tolerance", "level": "B2"},
    {"noun": "Kompromiss", "article": "der", "plural": "Kompromisse", "meaning": "compromise", "level": "B2"},
    {"noun": "Verhandlung", "article": "die", "plural": "Verhandlungen", "meaning": "negotiation, hearing", "level": "B2"},
    {"noun": "Vereinbarung", "article": "die", "plural": "Vereinbarungen", "meaning": "agreement, arrangement", "level": "B2"},
    {"noun": "Absicht", "article": "die", "plural": "Absichten", "meaning": "intention, purpose", "level": "B2"},
    {"noun": "Abschluss", "article": "der", "plural": "Abschlüsse", "meaning": "degree, qualification, conclusion", "level": "B2"},

    # Institutional, Economic & Scientific Structures
    {"noun": "Institution", "article": "die", "plural": "Institutionen", "meaning": "institution", "level": "B2"},
    {"noun": "Organisation", "article": "die", "plural": "Organisationen", "meaning": "organisation", "level": "B2"},
    {"noun": "Behörde", "article": "die", "plural": "Behörden", "meaning": "public authority, government agency", "level": "B2"},
    {"noun": "Verwaltung", "article": "die", "plural": "Verwaltungen", "meaning": "administration, management", "level": "B2"},
    {"noun": "Ministerium", "article": "das", "plural": "Ministerien", "meaning": "ministry, department", "level": "B2"},
    {"noun": "Parlament", "article": "das", "plural": "Parlamente", "meaning": "parliament", "level": "B2"},
    {"noun": "Verfassung", "article": "die", "plural": "Verfassungen", "meaning": "constitution, condition", "level": "B2"},
    {"noun": "Abgeordnete", "article": "der", "plural": "Abgeordneten", "meaning": "member of parliament (male)", "level": "B2"},
    {"noun": "Opposition", "article": "die", "plural": "Oppositionen", "meaning": "opposition", "level": "B2"},
    {"noun": "Koalition", "article": "die", "plural": "Koalitionen", "meaning": "coalition", "level": "B2"},
    {"noun": "Haushalt", "article": "der", "plural": "Haushalte", "meaning": "household, fiscal budget", "level": "B2"},
    {"noun": "Investition", "article": "die", "plural": "Investitionen", "meaning": "investment", "level": "B2"},
    {"noun": "Finanzen", "article": "die", "plural": "Finanzen", "meaning": "finances", "level": "B2"},
    {"noun": "Steuer", "article": "die", "plural": "Steuern", "meaning": "tax", "level": "B2"},
    {"noun": "Kredit", "article": "der", "plural": "Kredite", "meaning": "credit, bank loan", "level": "B2"},
    {"noun": "Schuld", "article": "die", "plural": "Schulden", "meaning": "debt, guilt", "level": "B2"},
    {"noun": "Gewinn", "article": "der", "plural": "Gewinne", "meaning": "profit, gain", "level": "B2"},
    {"noun": "Verlust", "article": "der", "plural": "Verluste", "meaning": "loss", "level": "B2"},
    {"noun": "Umsatz", "article": "der", "plural": "Umsätze", "meaning": "sales revenue, turnover", "level": "B2"},
    {"noun": "Wettbewerb", "article": "der", "plural": "Wettbewerbe", "meaning": "competition, rivalry", "level": "B2"},
    {"noun": "Konkurrenz", "article": "die", "plural": "Konkurrenzen", "meaning": "competition, rival", "level": "B2"},
    {"noun": "Marktwirtschaft", "article": "die", "plural": "Marktwirtschaften", "meaning": "market economy", "level": "B2"},
    {"noun": "Globalisierung", "article": "die", "plural": "Globalisierungen", "meaning": "globalisation", "level": "B2"},
    {"noun": "Digitalisierung", "article": "die", "plural": "Digitalisierungen", "meaning": "digitisation", "level": "B2"},
    {"noun": "Forschung", "article": "die", "plural": "Forschungen", "meaning": "research, scientific investigation", "level": "B2"},
    {"noun": "Wissenschaftler", "article": "der", "plural": "Wissenschaftler", "meaning": "scientist, researcher", "level": "B2"},
    {"noun": "Experiment", "article": "das", "plural": "Experimente", "meaning": "experiment", "level": "B2"},
    {"noun": "Labor", "article": "das", "plural": "Labore", "meaning": "laboratory", "level": "B2"},
    {"noun": "Hypothese", "article": "die", "plural": "Hypothesen", "meaning": "hypothesis", "level": "B2"},
    {"noun": "Theorie", "article": "die", "plural": "Theorien", "meaning": "theory", "level": "B2"},
    {"noun": "Phänomen", "article": "das", "plural": "Phänomene", "meaning": "phenomenon", "level": "B2"},
    {"noun": "Struktur", "article": "die", "plural": "Strukturen", "meaning": "structure", "level": "B2"},
    {"noun": "Funktion", "article": "die", "plural": "Funktionen", "meaning": "function, role", "level": "B2"},
    {"noun": "Prozess", "article": "der", "plural": "Prozesse", "meaning": "process, legal trial", "level": "B2"},
    {"noun": "System", "article": "das", "plural": "Systeme", "meaning": "system", "level": "B2"},
    {"noun": "Prinzip", "article": "das", "plural": "Prinzipien", "meaning": "principle", "level": "B2"},
    {"noun": "Faktor", "article": "der", "plural": "Faktoren", "meaning": "factor", "level": "B2"},
    {"noun": "Aspekt", "article": "der", "plural": "Aspekte", "meaning": "aspect", "level": "B2"}
]

# ----------------------------------------------------------------------
# C1 NOUNS: Advanced Academic, Nuanced, Literary & Philosophical (~100+ nouns)
# ----------------------------------------------------------------------
C1_NOUNS = [
    # Complex Abstract & Philosophical Concepts
    {"noun": "Erkenntnis", "article": "die", "plural": "Erkenntnisse", "meaning": "insight, cognitive recognition", "level": "C1"},
    {"noun": "Bewusstsein", "article": "das", "plural": "Bewusstsein", "meaning": "consciousness, awareness", "level": "C1"},
    {"noun": "Unterbewusstsein", "article": "das", "plural": "Unterbewusstsein", "meaning": "subconscious", "level": "C1"},
    {"noun": "Wahrnehmung", "article": "die", "plural": "Wahrnehmungen", "meaning": "perception, observation", "level": "C1"},
    {"noun": "Überzeugung", "article": "die", "plural": "Überzeugungen", "meaning": "conviction, persuasion", "level": "C1"},
    {"noun": "Auffassung", "article": "die", "plural": "Auffassungen", "meaning": "conception, view, interpretation", "level": "C1"},
    {"noun": "Schlussfolgerung", "article": "die", "plural": "Schlussfolgerungen", "meaning": "deduction, conclusion", "level": "C1"},
    {"noun": "Widerspruch", "article": "der", "plural": "Widersprüche", "meaning": "contradiction, discrepancy", "level": "C1"},
    {"noun": "Diskrepanz", "article": "die", "plural": "Diskrepanzen", "meaning": "discrepancy, divergence", "level": "C1"},
    {"noun": "Ambivalenz", "article": "die", "plural": "Ambivalenzen", "meaning": "ambivalence", "level": "C1"},
    {"noun": "Dilemma", "article": "das", "plural": "Dilemmata", "meaning": "dilemma", "level": "C1"},
    {"noun": "Plausibilität", "article": "die", "plural": "Plausibilitäten", "meaning": "plausibility", "level": "C1"},
    {"noun": "Authentizität", "article": "die", "plural": "Authentizitäten", "meaning": "authenticity", "level": "C1"},
    {"noun": "Souveränität", "article": "die", "plural": "Souveränitäten", "meaning": "sovereignty, composure", "level": "C1"},
    {"noun": "Integrität", "article": "die", "plural": "Integritäten", "meaning": "integrity", "level": "C1"},
    {"noun": "Legitimität", "article": "die", "plural": "Legitimitäten", "meaning": "legitimacy", "level": "C1"},
    {"noun": "Priorität", "article": "die", "plural": "Prioritäten", "meaning": "priority", "level": "C1"},
    {"noun": "Komplexität", "article": "die", "plural": "Komplexitäten", "meaning": "complexity", "level": "C1"},
    {"noun": "Diversität", "article": "die", "plural": "Diversitäten", "meaning": "diversity", "level": "C1"},
    {"noun": "Identität", "article": "die", "plural": "Identitäten", "meaning": "identity", "level": "C1"},
    {"noun": "Solidarität", "article": "die", "plural": "Solidaritäten", "meaning": "solidarity", "level": "C1"},
    {"noun": "Flexibilität", "article": "die", "plural": "Flexibilitäten", "meaning": "flexibility", "level": "C1"},
    {"noun": "Kreativität", "article": "die", "plural": "Kreativitäten", "meaning": "creativity", "level": "C1"},
    {"noun": "Produktivität", "article": "die", "plural": "Produktivitäten", "meaning": "productivity", "level": "C1"},
    {"noun": "Spontaneität", "article": "die", "plural": "Spontaneitäten", "meaning": "spontaneity", "level": "C1"},
    {"noun": "Intensität", "article": "die", "plural": "Intensitäten", "meaning": "intensity", "level": "C1"},
    {"noun": "Sensibilität", "article": "die", "plural": "Sensibilitäten", "meaning": "sensitivity", "level": "C1"},

    # Specialized Suffixes (-ismus, -tum, -nis, -ur, -um, -ment)
    {"noun": "Pragmatismus", "article": "der", "plural": "Pragmatismen", "meaning": "pragmatism", "level": "C1"},
    {"noun": "Individualismus", "article": "der", "plural": "Individualismen", "meaning": "individualism", "level": "C1"},
    {"noun": "Pluralismus", "article": "der", "plural": "Pluralismen", "meaning": "pluralism", "level": "C1"},
    {"noun": "Optimismus", "article": "der", "plural": "Optimismen", "meaning": "optimism", "level": "C1"},
    {"noun": "Pessimismus", "article": "der", "plural": "Pessimismen", "meaning": "pessimism", "level": "C1"},
    {"noun": "Realismus", "article": "der", "plural": "Realismen", "meaning": "realism", "level": "C1"},
    {"noun": "Kapitalismus", "article": "der", "plural": "Kapitalismen", "meaning": "capitalism", "level": "C1"},
    {"noun": "Sozialismus", "article": "der", "plural": "Sozialismen", "meaning": "socialism", "level": "C1"},
    {"noun": "Egoismus", "article": "der", "plural": "Egoismen", "meaning": "selfishness, egoism", "level": "C1"},
    {"noun": "Altruismus", "article": "der", "plural": "Altruismen", "meaning": "altruism", "level": "C1"},
    {"noun": "Konsens", "article": "der", "plural": "Konsense", "meaning": "consensus", "level": "C1"},
    {"noun": "Dissens", "article": "der", "plural": "Dissense", "meaning": "dissent, disagreement", "level": "C1"},
    {"noun": "Diskurs", "article": "der", "plural": "Diskurse", "meaning": "discourse, debate", "level": "C1"},
    {"noun": "Paradigma", "article": "das", "plural": "Paradigmen", "meaning": "paradigm", "level": "C1"},
    {"noun": "Kriterium", "article": "das", "plural": "Kriterien", "meaning": "criterion", "level": "C1"},
    {"noun": "Spektrum", "article": "das", "plural": "Spektren", "meaning": "spectrum, range", "level": "C1"},
    {"noun": "Gremium", "article": "das", "plural": "Gremien", "meaning": "committee, panel", "level": "C1"},
    {"noun": "Medium", "article": "das", "plural": "Medien", "meaning": "medium", "level": "C1"},
    {"noun": "Zentrum", "article": "das", "plural": "Zentren", "meaning": "center", "level": "C1"},
    {"noun": "Potential", "article": "das", "plural": "Potentiale", "meaning": "potential, capability", "level": "C1"},
    {"noun": "Defizit", "article": "das", "plural": "Defizite", "meaning": "deficit, shortfall", "level": "C1"},
    {"noun": "Engagement", "article": "das", "plural": "Engagements", "meaning": "commitment, social engagement", "level": "C1"},
    {"noun": "Ressource", "article": "die", "plural": "Ressourcen", "meaning": "resource", "level": "C1"},
    {"noun": "Nuance", "article": "die", "plural": "Nuancen", "meaning": "nuance, subtle shade", "level": "C1"},
    {"noun": "Tendenz", "article": "die", "plural": "Tendenzen", "meaning": "tendency, trend", "level": "C1"},
    {"noun": "Frequenz", "article": "die", "plural": "Frequenzen", "meaning": "frequency", "level": "C1"},
    {"noun": "Relevanz", "article": "die", "plural": "Relevanzen", "meaning": "relevance, significance", "level": "C1"},
    {"noun": "Dominanz", "article": "die", "plural": "Dominanzen", "meaning": "dominance", "level": "C1"},
    {"noun": "Konvergenz", "article": "die", "plural": "Konvergenzen", "meaning": "convergence", "level": "C1"},
    {"noun": "Divergenz", "article": "die", "plural": "Divergenzen", "meaning": "divergence", "level": "C1"},
    {"noun": "Affinität", "article": "die", "plural": "Affinitäten", "meaning": "affinity", "level": "C1"},
    {"noun": "Eloquenz", "article": "die", "plural": "Eloquenzen", "meaning": "eloquence", "level": "C1"},
    {"noun": "Kompetenz", "article": "die", "plural": "Kompetenzen", "meaning": "competence, proficiency", "level": "C1"},
    {"noun": "Souverän", "article": "der", "plural": "Souveräne", "meaning": "sovereign, ruler", "level": "C1"},
    {"noun": "Protagonist", "article": "der", "plural": "Protagonisten", "meaning": "protagonist, leading figure", "level": "C1"},
    {"noun": "Rezipient", "article": "der", "plural": "Rezipienten", "meaning": "recipient, receiver", "level": "C1"},
    {"noun": "Gutachten", "article": "das", "plural": "Gutachten", "meaning": "expert report, appraisal", "level": "C1"},
    {"noun": "Verfahren", "article": "das", "plural": "Verfahren", "meaning": "procedure, legal proceedings", "level": "C1"},
    {"noun": "Verhalten", "article": "das", "plural": "Verhalten", "meaning": "behaviour, conduct", "level": "C1"},
    {"noun": "Vermögen", "article": "das", "plural": "Vermögen", "meaning": "wealth, fortune, capability", "level": "C1"},
    {"noun": "Vorgehen", "article": "das", "plural": "Vorgehen", "meaning": "course of action, approach", "level": "C1"},
    {"noun": "Wohlbefinden", "article": "das", "plural": "Wohlbefinden", "meaning": "well-being", "level": "C1"}
]


def compile_all():
    # Save individual levels
    a1_path = DATA_DIR / "nouns_a1.json"
    a1_data = []
    if a1_path.exists():
        with open(a1_path, "r", encoding="utf-8") as f:
            a1_data = json.load(f)

    levels = {
        "nouns_a1.json": a1_data,
        "nouns_a2.json": A2_NOUNS,
        "nouns_b1.json": B1_NOUNS,
        "nouns_b2.json": B2_NOUNS,
        "nouns_c1.json": C1_NOUNS,
    }

    all_nouns = []
    seen_words = set()

    for filename, dataset in levels.items():
        # Remove any internal duplicates
        unique_dataset = []
        for item in dataset:
            noun_key = item["noun"].strip()
            if noun_key not in seen_words:
                seen_words.add(noun_key)
                unique_dataset.append(item)
        
        with open(DATA_DIR / filename, "w", encoding="utf-8") as f:
            json.dump(unique_dataset, f, ensure_ascii=False, indent=2)
        print(f"✅ {filename}: {len(unique_dataset)} nouns")
        all_nouns.extend(unique_dataset)

    # Save combined dataset
    with open(DATA_DIR / "nouns_a1_to_c1.json", "w", encoding="utf-8") as f:
        json.dump(all_nouns, f, ensure_ascii=False, indent=2)

    print(f"\n🎉 Compiled Master Dataset: {len(all_nouns)} nouns ({len(all_nouns)*2} cards) across CEFR A1-C1!")


if __name__ == "__main__":
    compile_all()
